title: Reading Joggers
baseurl: ""
url: "https://readingjoggers.org/"
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
   - appveyor.yml
   - README.md
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/