version: 2.0.{build}
build: on
build_script:
- ps: Remove-item .\* -exclude "_site", ".git" -Force -ErrorAction SilentlyContinue -Recurse -Verbose
- ps: robocopy .\_site\ (Get-Location) & exit 0
- ps: Remove-Item _site -Force -Recurse -Verbose
artifacts:
  - path: '**/*'
deploy:
- provider: FTP
  host:  ftp.readingjoggers.org
  protocol: ftp
  username: rjadmin@boxwebs.co.uk
  password:
    secure: lDrcdb+gMhuq7xDg8Yt6Cg==
  folder: /
  active_mode: false
  beta: true
  debug: true