version: 2.0.{build}
build: on
build_script:
- ps: Get-ChildItem -Path (Get-Location) -Recurse | Select -ExpandProperty FullName | Where {$_ -notlike '*_site*'} | sort length -Descending | Remove-Item -force -Verbose
- cmd: robocopy .\_site\ . /E & exit 0
- ps: Remove-Item _site -Force -Recurse -Verbose
artifacts:
  - path: '**/*'
deploy:
- provider: FTP
  host:  ftp.readingjoggers.org
  protocol: ftp
  username: rjadmin@boxwebs.co.uk
  password:
    secure: lDrcdb+gMhuq7xDg8Yt6Cg==
  folder: /
  active_mode: false
  beta: true
  debug: true
