version: 2.0.{build}
build: on
build_script:
- cmd: echo "Building"
artifacts:
  - path: '**/*'
after_build:
- ps: Remove-Item -Recurse (Get-Location) -Exclude _site
- cmd: move .\_site\*.* .\*.* /Y
deploy:
- provider: FTP
  host:  ftp.readingjoggers.org
  protocol: ftp
  username: rjadmin@boxwebs.co.uk
  password:
    secure: lDrcdb+gMhuq7xDg8Yt6Cg==
  folder: /
  active_mode: false
  beta: true
  debug: true