version: 2.0.{build}
image: Visual Studio 2017
build: on
branches:
  only:
  - appveyor
install:
- cmd: set PATH=C:\Ruby22\bin;%PATH%
- cmd: gem install bundler
- cmd: gem install jekyll
build_script:
- cmd: bundle exec jekyll build
artifacts:
  - path: '**/*'
deploy:
- provider: FTP
  host: ftp.readingjoggers.org
  protocol: ftp
  username: rjadmin@readingjoggers.org
  password:
    secure: lDrcdb+gMhuq7xDg8Yt6Cg==
  folder: /
  active_mode: false
  beta: true
  debug: true
notifications:
- provider: Email
  to:
  - tom@tjrobinson.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true