version: 2.0.{build}
build: off
artifacts:
  - path: '_site/**/*'
after_build:
- cmd: copy _site\*.* .\*.* /Y
deploy:
- provider: FTP
  host:  ftp.readingjoggers.org
  protocol: ftp
  username: rjadmin@boxwebs.co.uk
  password:
    secure: lDrcdb+gMhuq7xDg8Yt6Cg==
  folder: /
  active_mode: false
  beta: true
  debug: true